In [1]:
# Imports
%load_ext autoreload
%autoreload 2

import re
import yaml
import numpy as np
import pandas as pd

import lts_functions as lts
import LTS_OSM

# Using jupyter notebooks with a virtual environment
# https://anbasile.github.io/posts/2017-06-25-jupyter-venv/
# https://stackoverflow.com/questions/58119823/jupyter-notebooks-in-visual-studio-code-does-not-use-the-active-virtual-environm
# ipython kernel install --user --name=.venv

In [2]:
# Settings
region = 'Boston'
unit = 'english'

rating_dict = lts.read_rating()
tables = lts.read_tables()

In [9]:
# Load Data
gdfNodes, gdfEdges = LTS_OSM.download_data(region)

Loading saved graph for Boston
gdf_edges.shape=(429861, 270)
gdf_nodes.shape=(209424, 6)


In [10]:
rating_dict = lts.read_rating()
gdf_biking_permitted = lts.biking_permitted(gdfEdges.copy(), rating_dict)

ruleName = 'biking_permitted'
rules_used = gdf_biking_permitted[f'{ruleName}_rule_num_left'].tolist()
rules_used += gdf_biking_permitted[f'{ruleName}_rule_num_right'].tolist()
rules_used = list(set(rules_used))
rules_used = [int(s[len(ruleName):]) for s in rules_used]
rules_used.sort()
print(rules_used)

[0, 1, 2, 4, 6, 8, 14, 18, 20, 21, 22, 23, 26, 28, 30, 32, 34, 36]


In [11]:
# get the columns that start with 'cycleway'
cycleway_tags = gdfEdges.columns[gdfEdges.columns.str.contains('cycleway')]
# print(cycleway_tags)

for tag in cycleway_tags.sort_values():
    print(tag, gdfEdges[tag].unique())

check_date:cycleway [nan '2021-12-29']
cycleway [nan 'lane' 'shared_lane' 'separate' 'track' 'no' 'share_busway'
 'crossing']
cycleway:both [nan 'lane' 'no' 'shared_lane' 'separate' 'track']
cycleway:both:buffer [nan 'no' 'yes']
cycleway:both:lane [nan 'exclusive' 'advisory' 'pictogram']
cycleway:buffer [nan 'no' 'yes']
cycleway:lane [nan 'exclusive' 'advisory' 'pictogram']
cycleway:left [nan 'lane' 'shared_lane' 'no' 'track' 'share_busway' 'separate']
cycleway:left:buffer [nan 'no' 'yes']
cycleway:left:lane [nan 'exclusive' 'advisory' 'pictogram']
cycleway:left:oneway [nan '-1' 'yes' 'no']
cycleway:left:separation [nan 'flex_post']
cycleway:right [nan 'no' 'lane' 'shared_lane' 'track' 'share_busway' 'separate']
cycleway:right:buffer [nan 'no' 'yes']
cycleway:right:lane [nan 'pictogram' 'exclusive' 'advisory']
cycleway:right:oneway [nan 'no' 'yes']
cycleway:right:separation [nan 'flex_post' 'no' 'flex_post\\']
cycleway:separation [nan 'flex_post']
cycleway:surface [nan 'concrete' 'asph

In [12]:
rating_dict = lts.read_rating()
gdf_separated_edges = lts.is_separated_path(gdf_biking_permitted.copy(), rating_dict)

ruleName = 'bike_lane_separation'
rules_used = gdf_separated_edges[f'{ruleName}_rule_num_left'].unique().tolist()
rules_used += gdf_separated_edges[f'{ruleName}_rule_num_right'].unique().tolist()
rules_used = list(set(rules_used))
rules_used = [int(s[len(ruleName):]) for s in rules_used]
rules_used.sort()
print(rules_used)

[0, 1, 2, 3, 4, 8]


In [13]:
# get the columns that start with 'cycleway'
cycleway_tags = gdfEdges.columns[gdfEdges.columns.str.contains('cycleway')]
# print(cycleway_tags)

for tag in cycleway_tags.sort_values():
    print(tag, gdfEdges[tag].unique())

# print('shoulder:access:bicycle', gdfEdges['shoulder:access:bicycle'].unique())

check_date:cycleway [nan '2021-12-29']
cycleway [nan 'lane' 'shared_lane' 'separate' 'track' 'no' 'share_busway'
 'crossing']
cycleway:both [nan 'lane' 'no' 'shared_lane' 'separate' 'track']
cycleway:both:buffer [nan 'no' 'yes']
cycleway:both:lane [nan 'exclusive' 'advisory' 'pictogram']
cycleway:buffer [nan 'no' 'yes']
cycleway:lane [nan 'exclusive' 'advisory' 'pictogram']
cycleway:left [nan 'lane' 'shared_lane' 'no' 'track' 'share_busway' 'separate']
cycleway:left:buffer [nan 'no' 'yes']
cycleway:left:lane [nan 'exclusive' 'advisory' 'pictogram']
cycleway:left:oneway [nan '-1' 'yes' 'no']
cycleway:left:separation [nan 'flex_post']
cycleway:right [nan 'no' 'lane' 'shared_lane' 'track' 'share_busway' 'separate']
cycleway:right:buffer [nan 'no' 'yes']
cycleway:right:lane [nan 'pictogram' 'exclusive' 'advisory']
cycleway:right:oneway [nan 'no' 'yes']
cycleway:right:separation [nan 'flex_post' 'no' 'flex_post\\']
cycleway:separation [nan 'flex_post']
cycleway:surface [nan 'concrete' 'asph

In [ ]:
rating_dict = lts.read_rating()
gdf_bike_lanes = lts.is_bike_lane(gdf_separated_edges.copy(), rating_dict)

ruleName = 'bike_lane_exist'
rules_used = gdf_bike_lanes[f'{ruleName}_rule_num_left'].tolist()
rules_used += gdf_bike_lanes[f'{ruleName}_rule_num_right'].tolist()
rules_used = list(set(rules_used))
rules_used = [int(s[len(ruleName):]) for s in rules_used]
rules_used.sort()
print(rules_used)


In [18]:
tags = gdfEdges.columns[gdfEdges.columns.str.contains('parking')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

parking:both [nan 'lane' 'no' 'street_side' 'separate']
parking:both:orientation [nan 'parallel' 'diagonal']
parking:condition:both [nan 'no_stopping' 'residents' 'customers']
parking:condition:both:customers [nan 'CVS']
parking:condition:both:maxstay [nan '2 hours']
parking:condition:both:time_interval [nan 'Mo-Fr 08:00-18:00' '08:00-18:00']
parking:condition:left [nan 'free' 'no_parking' 'residents' 'ticket']
parking:condition:left:maxstay [nan '2 hours']
parking:condition:left:time_interval [nan 'Mo-Fr 08:00-18:00']
parking:condition:right [nan 'free' 'customers']
parking:condition:right:maxstay [nan '2 hours']
parking:condition:right:time_interval [nan 'Mo-Fr 08:00-18:00' '08:00-18:00']
parking:lane [nan 'no_parking']
parking:lane:both [nan 'no_stopping' 'parallel' 'no' 'no_parking' 'diagonal']
parking:lane:both:parallel [nan 'on_street']
parking:lane:both_1 [nan 'parallel']
parking:lane:left [nan 'parallel' 'no_stopping' 'no_parking' 'no']
parking:lane:left:parallel [nan 'on_stree

In [22]:
rating_dict = lts.read_rating()
gdf_parking = lts.parking_present(gdf_bike_lanes.copy(), rating_dict)

ruleName = 'parking'
rules_used = gdf_parking[f'{ruleName}_rule_num_left'].tolist()
rules_used += gdf_parking[f'{ruleName}_rule_num_right'].tolist()
rules_used = list(set(rules_used))
rules_used = [int(s[len(ruleName):]) for s in rules_used]
rules_used.sort()
print(rules_used)

['parking9', 'parking6', 'parking8', 'parking5', 'parking3', 'parking0', 'parking10', 'parking7', 'parking2', 'parking1', 'parking4']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [23]:
tags = gdfEdges.columns[gdfEdges.columns.str.contains('speed')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

print('\n---\n')
tags = gdfEdges.columns[gdfEdges.columns.str.contains('highway')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

maxspeed ['25 mph' nan '20 mph' '35 mph' '30 mph' '24 mph' '10 mph' '40 mph'
 '5 mph' '15 mph' 'signals' '45 mph' '6 mph' '7 mph' '55 mph' '3 mph']
maxspeed:advisory [nan '15 mph' '5 mph']
maxspeed:bus [nan '20 mph']
maxspeed:hgv [nan '20 mph']
maxspeed:type [nan 'sign' 'US:urban']
maxspeed:variable [nan 'school_zone']
source:maxspeed [nan 'massgis' 'Massachusetts General Law 90-17' 'survey']

---

area:highway [nan 'traffic_island']
highway ['residential' 'footway' 'secondary' 'trunk' 'primary' 'service'
 'tertiary' 'unclassified' 'cycleway' 'construction' 'trunk_link'
 'primary_link' 'path' 'pedestrian' 'secondary_link' 'track'
 'tertiary_link' 'living_street' 'busway' 'emergency_bay']


In [24]:
print(gdfEdges[gdfEdges['highway'] == 'primary']['maxspeed'].unique())

[nan '35 mph' '25 mph' '30 mph' '40 mph' '55 mph']


In [27]:
rating_dict = lts.read_rating()
gdf_speed = lts.get_prevailing_speed(gdf_parking.copy(), rating_dict)

ruleName = 'speed'
rules_used = gdf_speed[f'{ruleName}_rule_num'].unique().tolist()
rules_used = [int(s[len(ruleName):]) for s in rules_used]
rules_used.sort()
print(rules_used)

print(gdf_speed['speed'].unique())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[25 15 35 50 30 20  0 40 24 10  5 45  6  7 55  3]


In [28]:
print(gdfEdges['lanes'].unique())

[nan '2' '3' '1' '4' '5' '7' '6']


In [29]:
rating_dict = lts.read_rating()
gdf_lanes = lts.get_lanes(gdf_speed.copy())

In [30]:
print(gdf_lanes['lane_count'].unique())

[2 3 1 4 5 7 6]


In [31]:
tags = gdfEdges.columns[gdfEdges.columns.str.contains('lane_markings')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

lane_markings ['no' nan 'yes']


In [33]:
rating_dict = lts.read_rating()
gdf_centerlines = lts.get_centerlines(gdf_lanes.copy(), rating_dict)

ruleName = 'centerline'
rules_used = gdf_centerlines[f'{ruleName}_rule_num'].unique().tolist()
rules_used = [int(s[len(ruleName):]) for s in rules_used]
rules_used.sort()
print(rules_used)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [34]:
tags = gdfEdges.columns[gdfEdges.columns.str.contains('width')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

tags = gdfEdges.columns[gdfEdges.columns.str.contains('buffer')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

cycleway:width [nan '5\'10"']
source:width [nan 'ARCore']
width [nan '9.8' '21.3' '19.5' '28.0' '30.5' '22.0' '12.2' '11.9' '18.9' '12.8'
 '11.0' '13.4' '19.8' '10.1' '9.1' '20.1' '18.3' '10.4' '36.6' '11.6'
 '17.4' '12.5' '24.4' '15.9' '25.9' '15.2' '15.5' '10.7' '18.0' '8.5'
 '21.6' '14.9' '7.3' '27.4' '6.7' '17.1' '7.9' '6' '31.1' '29.6'
 '15.2;38.1' '6.1' '23.2' '33.5' '11.3' '16.8' '5' '18.6' '30.2' '9.5'
 '4.3' '4.5' '14.6' '14.0' '16.5' '10' '8.8' '14.3' '22.9' '6.5' '29.9'
 '4.9' '7.6' '29.0' '28.7' '7.8' '22.6' '20.7' '32.0' '3.7' '3' '3.5' '11'
 '8' '13.1' '13.7' '42.7' '27.1' '5.5' '7.7' '36.0' '32.6' '59.1' '25.6'
 '20.4' '4.1' '14.0; 15.2' '47.0' '16.2' '25.0' '7.0' '27.7' '5.8' '5.2'
 '23.8; 15.9' '6.4' '23.8' '26.5' '17.7' '41.5' '26.8' '19.2' '29' '24.7'
 '24.4;15.2' '7' '45.7' '22.4' '3.4' '21.0' '6\'0"' '22.3' '17.7;11.0'
 '8.2' '23.5' '26.2' '43.9' '51.8' '4.6' '3.0' '2.0' '9.2' '2.5' '9'
 '39.3' '2.7' '4' '6.8' '39.9' '6.2' '76.2' '35.1' '2.4' '11.5' '11.8'
 '30.8' 

In [35]:
gdf_width_ft = lts.width_ft(gdf_centerlines.copy())

In [37]:
streetWidth = gdf_width_ft['width_street'].unique()
cyclewayWidth = list(set(gdf_width_ft['width_bikelane_left'] + gdf_width_ft['width_bikelane_right']))

streetWidth.sort()
cyclewayWidth.sort()

print(streetWidth)
print(cyclewayWidth)

[  1.64042      3.28084      4.265092     4.593176     4.92126
   6.           6.33333333   6.56168      7.217848     7.545932
   7.874016     8.2021       8.858268     9.33333333   9.84252
  10.170604    10.33333333  10.498688    10.66666667  10.826772
  11.154856    11.48294     11.811024    12.139108    13.12336
  13.451444    13.779528    14.107612    14.76378     15.091864
  15.419948    16.076116    16.4042      17.060368    18.04462
  18.700788    19.028872    19.356956    19.68504     20.013124
  20.341208    20.997376    21.32546     21.981628    22.309712
  22.96588     23.293964    23.950132    24.278216    24.6063
  24.934384    25.262468    25.590552    25.918636    26.24672
  26.902888    27.88714     28.871392    29.52756     29.855644
  30.183728    30.511812    30.839896    31.16798     31.98819
  32.152232    32.8084      33.136484    33.792652    34.120736
  35.104988    36.08924     36.745408    37.073492    37.72966
  38.057744    38.713912    39.041996    39.37008

In [38]:
tags = gdfEdges.columns[gdfEdges.columns.str.contains('one')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

tags = gdf_width_ft.columns[gdf_width_ft.columns.str.contains('parking')]
for tag in tags.sort_values():
    print(tag, gdf_width_ft[tag].unique())

abandoned:service [nan 'siding']
cycleway:left:oneway [nan '-1' 'yes' 'no']
cycleway:oneway [nan 'yes']
cycleway:right:oneway [nan 'no' 'yes']
oneway [ True False]
oneway:bicycle [nan 'no' 'yes']
oneway:bus [nan 'no']
oneway:conditional [nan 'yes @ (18:00-06:00)']
source:oneway [nan 'survey']
parking:both [nan 'lane' 'no' 'street_side' 'separate']
parking:both:orientation [nan 'parallel' 'diagonal']
parking:condition:both [nan 'no_stopping' 'residents' 'customers']
parking:condition:both:customers [nan 'CVS']
parking:condition:both:maxstay [nan '2 hours']
parking:condition:both:time_interval [nan 'Mo-Fr 08:00-18:00' '08:00-18:00']
parking:condition:left [nan 'free' 'no_parking' 'residents' 'ticket']
parking:condition:left:maxstay [nan '2 hours']
parking:condition:left:time_interval [nan 'Mo-Fr 08:00-18:00']
parking:condition:right [nan 'free' 'customers']
parking:condition:right:maxstay [nan '2 hours']
parking:condition:right:time_interval [nan 'Mo-Fr 08:00-18:00' '08:00-18:00']
parkin

In [39]:
rating_dict = lts.read_rating()
gdf_nw = lts.define_narrow_wide(gdf_width_ft.copy())

In [40]:
rating_dict = lts.read_rating()
gdf_adt = lts.define_adt(gdf_nw.copy(), rating_dict)

In [41]:
print(gdf_adt['lane_count'].unique())
print(gdf_adt['speed'].unique())
print(gdf_adt['ADT'].unique())

[2 3 1 4 5 7 6]
[25 15 35 50 30 20  0 40 24 10  5 45  6  7 55  3]
[ 749   10 1501 8001 3001  100  599 1001 1500]


In [42]:
tags = gdf_adt.columns[gdf_adt.columns.str.contains('contra')]
for tag in tags.sort_values():
    print(tag, gdf_adt[tag].unique())

In [45]:
rating_dict = lts.read_rating()
tables = lts.read_tables()
gdf_lts = lts.calculate_lts(gdf_adt.copy(), tables)

['table_mixed_1', 'table_mixed_2', 'table_mixed_3', 'table_mixed_4', 'table_mixed_5']
['table_bikelane_noparking_1', 'table_bikelane_noparking_2', 'table_bikelane_noparking_3']
['table_bikelane_yesparking_1', 'table_bikelane_yesparking_2', 'table_bikelane_yesparking_3', 'table_bikelane_yesparking_4']


In [36]:
print(f"{gdf_lts['LTS'].unique()=}")
print(f"{gdf_lts['LTS_mixed'].unique()=}")
print(f"{gdf_lts['centerline'].unique()=}")
print(f"{gdf_lts['lane_count'].unique()=}")
print(f"{gdf_lts['oneway'].unique()=}")

gdf_lts['LTS'].unique()=array([ 1.,  3.,  2., nan,  4.,  0.])
gdf_lts['LTS_mixed'].unique()=array([ 2.,  1.,  3., nan,  4.])
gdf_lts['centerline'].unique()=array(['no', 'yes'], dtype=object)
gdf_lts['lane_count'].unique()=array([2, 1, 3, 4, 5, 7])
gdf_lts['oneway'].unique()=array([False,  True])
