In [1]:
# Imports
%load_ext autoreload
%autoreload 2

import re
import yaml
import numpy as np
import pandas as pd

import lts_functions as lts
import LTS_OSM

# Using jupyter notebooks with a virtual environment
# https://anbasile.github.io/posts/2017-06-25-jupyter-venv/
# https://stackoverflow.com/questions/58119823/jupyter-notebooks-in-visual-studio-code-does-not-use-the-active-virtual-environm
# ipython kernel install --user --name=.venv

In [2]:
# Settings
region = 'Cambridge'
unit = 'english'

rating_dict = lts.read_rating()
tables = lts.read_tables()

In [3]:
# Load Data
gdfNodes, gdfEdges = LTS_OSM.download_data(region)

Loading saved graph for Cambridge
gdf_edges.shape=(104947, 191)
gdf_nodes.shape=(48058, 6)


In [5]:
rating_dict = lts.read_rating()
gdf_biking_permitted = lts.biking_permitted(gdfEdges.copy(), rating_dict)

rules_used = gdf_biking_permitted['biking_permitted_rule_num'].unique().tolist()
rules_used = [int(s[16:]) for s in rules_used]
rules_used.sort()
print(rules_used)

[0, 1, 5, 6]


In [6]:
# get the columns that start with 'cycleway'
cycleway_tags = gdfEdges.columns[gdfEdges.columns.str.contains('cycleway')]
# print(cycleway_tags)

for tag in cycleway_tags.sort_values():
    print(tag, gdfEdges[tag].unique())

check_date:cycleway [nan '2022-02-18' '2021-09-25' '2023-06-09']
cycleway [nan 'shared_lane' 'no' 'lane' 'separate' 'crossing' 'shared' 'track'
 'construction']
cycleway:both [nan 'no' 'shared_lane' 'separate' 'lane' 'share_busway']
cycleway:both:buffer [nan 'no' 'yes']
cycleway:both:lane [nan 'pictogram' 'exclusive' 'advisory']
cycleway:buffer [nan "2'"]
cycleway:lanes:backward [nan 'none|none|lane']
cycleway:left [nan 'shared_lane' 'no' 'separate' 'track' 'lane' 'share_busway']
cycleway:left:buffer [nan 'yes']
cycleway:left:lane [nan 'exclusive' 'pictogram']
cycleway:left:oneway [nan '-1' 'no']
cycleway:left:separation [nan 'buffer' 'flex_post']
cycleway:right [nan 'lane' 'separate' 'no' 'track' 'shared_lane' 'shoulder'
 'share_busway' 'buffered_lane']
cycleway:right:buffer [nan 'yes']
cycleway:right:lane [nan 'exclusive' 'pictogram' 'advisory']
cycleway:right:oneway [nan 'no']
cycleway:right:separation [nan 'flex_post']
cycleway:surface [nan 'asphalt']
cycleway:width [nan "5'" '6\'0

In [7]:
rating_dict = lts.read_rating()
gdf_separated_edges = lts.is_separated_path(gdf_biking_permitted.copy(), rating_dict)

rules_used = gdf_separated_edges['bike_lane_separation_rule_num'].unique().tolist()
rules_used = [int(s[20:]) for s in rules_used]
rules_used.sort()
print(rules_used)

[0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11]


In [8]:
# get the columns that start with 'cycleway'
cycleway_tags = gdfEdges.columns[gdfEdges.columns.str.contains('cycleway')]
# print(cycleway_tags)

for tag in cycleway_tags.sort_values():
    print(tag, gdfEdges[tag].unique())

# print('shoulder:access:bicycle', gdfEdges['shoulder:access:bicycle'].unique())

check_date:cycleway [nan '2022-02-18' '2021-09-25' '2023-06-09']
cycleway [nan 'shared_lane' 'no' 'lane' 'separate' 'crossing' 'shared' 'track'
 'construction']
cycleway:both [nan 'no' 'shared_lane' 'separate' 'lane' 'share_busway']
cycleway:both:buffer [nan 'no' 'yes']
cycleway:both:lane [nan 'pictogram' 'exclusive' 'advisory']
cycleway:buffer [nan "2'"]
cycleway:lanes:backward [nan 'none|none|lane']
cycleway:left [nan 'shared_lane' 'no' 'separate' 'track' 'lane' 'share_busway']
cycleway:left:buffer [nan 'yes']
cycleway:left:lane [nan 'exclusive' 'pictogram']
cycleway:left:oneway [nan '-1' 'no']
cycleway:left:separation [nan 'buffer' 'flex_post']
cycleway:right [nan 'lane' 'separate' 'no' 'track' 'shared_lane' 'shoulder'
 'share_busway' 'buffered_lane']
cycleway:right:buffer [nan 'yes']
cycleway:right:lane [nan 'exclusive' 'pictogram' 'advisory']
cycleway:right:oneway [nan 'no']
cycleway:right:separation [nan 'flex_post']
cycleway:surface [nan 'asphalt']
cycleway:width [nan "5'" '6\'0

In [10]:
rating_dict = lts.read_rating()
gdf_bike_lanes = lts.is_bike_lane(gdf_separated_edges.copy(), rating_dict)

rules_used = gdf_bike_lanes['bike_lane_exist_rule_num'].unique().tolist()
rules_used = [int(s[15:]) for s in rules_used]
rules_used.sort()
print(rules_used)


[0, 1, 2, 3, 4]


In [11]:
tags = gdfEdges.columns[gdfEdges.columns.str.contains('parking')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

parking:both [nan 'no' 'lane' 'separate' 'street_side']
parking:both:orientation [nan 'parallel']
parking:condition:both [nan 'no_parking' 'no_stopping' 'ticket;residents']
parking:condition:left [nan 'no_parking' 'residents' 'ticket;residents']
parking:condition:right [nan 'no_parking' 'residents']
parking:lane:both [nan 'parallel' 'no_stopping' 'no']
parking:lane:both:parallel [nan 'on_street']
parking:lane:left [nan 'parallel' 'no_stopping' 'no']
parking:lane:left:parallel [nan 'on_street']
parking:lane:right [nan 'no_stopping' 'parallel' 'no']
parking:lane:right:parallel [nan 'on_street' 'painted_area_only']
parking:left [nan 'no' 'lane' 'separate' 'street_side']
parking:left:orientation [nan 'parallel']
parking:left:restriction [nan 'no_stopping']
parking:right [nan 'lane' 'no' 'separate' 'street_side']
parking:right:access [nan 'permit']
parking:right:fee [nan 'yes']
parking:right:orientation [nan 'parallel']


In [13]:
rating_dict = lts.read_rating()
gdf_parking = lts.parking_present(gdf_bike_lanes.copy(), rating_dict)

rules_used = gdf_parking['parking_rule_num'].unique().tolist()
rules_used = [int(s[7:]) for s in rules_used]
rules_used.sort()
print(rules_used)

[0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 21, 22, 23, 24, 26, 28, 29, 30, 41, 42, 44, 50]


In [14]:
tags = gdfEdges.columns[gdfEdges.columns.str.contains('speed')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

print('\n---\n')
tags = gdfEdges.columns[gdfEdges.columns.str.contains('highway')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

maxspeed [nan '25 mph' '30 mph' '20 mph' '15 mph' '35 mph' '25' '40 mph' '20'
 '55 mph' '10 mph' '5 mph']
maxspeed:advisory [nan '5 mph']
maxspeed:type [nan 'US:urban' 'sign']
source:maxspeed [nan 'massgis']

---

area:highway [nan 'traffic_island' 'yes']
construction:highway [nan 'cycleway']
highway ['footway' 'residential' 'secondary' 'unclassified' 'trunk' 'service'
 'tertiary' 'primary' 'cycleway' 'path' 'primary_link' 'pedestrian'
 'trunk_link' 'tertiary_link' 'secondary_link' 'construction'
 'living_street' 'busway' 'track']
note:highway [nan 'busway']


In [15]:
print(gdfEdges[gdfEdges['highway'] == 'primary']['maxspeed'].unique())

['25 mph' nan '35 mph' '25' '20 mph' '40 mph' '30 mph']


In [17]:
rating_dict = lts.read_rating()
gdf_speed = lts.get_prevailing_speed(gdf_parking.copy(), rating_dict)

rules_used = gdf_speed['speed_rule_num'].unique().tolist()
rules_used = [int(s[5:]) for s in rules_used]
rules_used.sort()
print(rules_used)

print(gdf_speed['speed'].unique())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[25 30 20 35 40 50 15  0 55 10  5]


In [18]:
print(gdfEdges['lanes'].unique())

[nan '2' '1' '3' '4' '5' '7']


In [19]:
rating_dict = lts.read_rating()
gdf_lanes = lts.get_lanes(gdf_speed.copy())

In [20]:
print(gdf_lanes['lane_count'].unique())

[2 1 3 4 5 7]


In [21]:
tags = gdfEdges.columns[gdfEdges.columns.str.contains('lane_markings')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

lane_markings [nan 'no' 'yes']


In [23]:
rating_dict = lts.read_rating()
gdf_centerlines = lts.get_centerlines(gdf_lanes.copy(), rating_dict)

rules_used = gdf_centerlines['centerline_rule_num'].unique().tolist()
rules_used = [int(s[10:]) for s in rules_used]
rules_used.sort()
print(rules_used)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [24]:
tags = gdfEdges.columns[gdfEdges.columns.str.contains('width')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

tags = gdfEdges.columns[gdfEdges.columns.str.contains('buffer')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

cycleway:width [nan "5'" '6\'0"' '3\'0"']
source:width [nan 'ARCore']
width [nan '7.6' '9.5' '15.2' '21.3' '14.9' '12.2' '11.6' '30.5' '18.9' '20.7'
 '11.0' '7.3' '15.9' '9.1' '17\'0"' '11.9' '20\'0"' '17.1' '24.4' '14.0'
 '18.3' '24\'0"' '30.2' '14.6' '15.2;18.6' '13.4' '25.9' '6.7' '28.0'
 '36.6' '16.8' '3.7' '19.8' '10.4;12.2' '11.7' '4.3' '4.6' '8.5' '12.8'
 '10.4' '15.5' '13.7' '6.1' '25.6' '9.8' '4.9' '26.8' '3.0' '11.3' '5.5'
 '10.7' '19.2' '7.9' '5.8' '8.2' '10.1' '28\'0"' '20.1' '18.6' '6.4' '5.2'
 '16.5' '14.3' '17.7' '19.5' '38.1' '8.8' '22.9' '30\'0"' '16.2' '4.7'
 '16.8;15.2' '7' '2' '12.5' '46\'0"' '50\'0"' '16.1' '27\'0"' '91.5'
 '18.0' '11.6;10.4' '5' '27.4' '8\'0"' '3.3' '3' '3.5' '8\'8"' '5\'0"' '6'
 '21\'0"' "10'" '1' '2.7' '1.5' '9\'0"' '8' '10\'0"' '12\'0"' '1.4' "8'"
 '7.0' '1.8' '6\'0"' '16\'0"']
width:carriageway [nan '9' '8']
width:lanes [nan '3|3']
cycleway:both:buffer [nan 'no' 'yes']
cycleway:buffer [nan "2'"]
cycleway:left:buffer [nan 'yes']
cycleway:right:

In [25]:
gdf_width_ft = lts.width_ft(gdf_centerlines.copy())

In [26]:
streetWidth = gdf_width_ft['width_street'].unique()
cyclewayWidth = gdf_width_ft['width_bikelane'].unique()

streetWidth.sort()
cyclewayWidth.sort()

print(streetWidth)
print(cyclewayWidth)

[  3.28084      4.593176     4.92126      5.           5.905512
   6.           6.56168      8.           8.66666667   8.858268
   9.           9.84252     10.          10.826772    11.48294
  12.          12.139108    14.107612    15.091864    15.419948
  16.          16.076116    16.4042      17.          17.060368
  18.04462     19.028872    19.68504     20.          20.013124
  20.997376    21.          21.981628    22.96588     23.950132
  24.          24.934384    25.918636    26.24672     26.902888
  27.          27.88714     28.          28.871392    29.855644
  30.          31.16798     32.152232    33.136484    34.120736
  35.104988    36.08924     37.073492    38.057744    38.385828
  39.041996    40.026248    41.0105      41.994752    43.963256
  44.947508    45.93176     46.          46.916012    47.900264
  48.884516    49.868768    50.          50.85302     52.165356
  52.821524    53.149608    54.13386     55.118112    56.102364
  58.070868    59.05512     60.039372    

In [27]:
tags = gdfEdges.columns[gdfEdges.columns.str.contains('one')]
for tag in tags.sort_values():
    print(tag, gdfEdges[tag].unique())

tags = gdf_width_ft.columns[gdf_width_ft.columns.str.contains('parking')]
for tag in tags.sort_values():
    print(tag, gdf_width_ft[tag].unique())

cycleway:left:oneway [nan '-1' 'no']
cycleway:right:oneway [nan 'no']
oneway [False  True]
oneway:bicycle [nan 'no' 'yes']
oneway:conditional [nan '-1 @ (17:00-19:00); ' 'yes @ (07:00-09:00,15:00-19:00)']
parking ['yes' 'no' 'left:no' 'left:yes' 'right:no' 'right:yes']
parking:both [nan 'no' 'lane' 'separate' 'street_side']
parking:both:orientation [nan 'parallel']
parking:condition:both [nan 'no_parking' 'no_stopping' 'ticket;residents']
parking:condition:left [nan 'no_parking' 'residents' 'ticket;residents']
parking:condition:right [nan 'no_parking' 'residents']
parking:lane:both [nan 'parallel' 'no_stopping' 'no']
parking:lane:both:parallel [nan 'on_street']
parking:lane:left [nan 'parallel' 'no_stopping' 'no']
parking:lane:left:parallel [nan 'on_street']
parking:lane:right [nan 'no_stopping' 'parallel' 'no']
parking:lane:right:parallel [nan 'on_street' 'painted_area_only']
parking:left [nan 'no' 'lane' 'separate' 'street_side']
parking:left:orientation [nan 'parallel']
parking:left

In [28]:
# This is new.
rating_dict = lts.read_rating()
gdf_nw = lts.define_narrow_wide(gdf_width_ft.copy())

In [30]:
rating_dict = lts.read_rating()
gdf_adt = lts.define_adt(gdf_nw.copy(), rating_dict)

In [31]:
print(gdf_adt['lane_count'].unique())
print(gdf_adt['speed'].unique())
print(gdf_adt['ADT'].unique())

[2 1 3 4 5 7]
[25 30 20 35 40 50 15  0 55 10  5]
[3001  749  599 1501 8001 1001]


In [32]:
tags = gdf_adt.columns[gdf_adt.columns.str.contains('contra')]
for tag in tags.sort_values():
    print(tag, gdf_adt[tag].unique())

In [35]:
rating_dict = lts.read_rating()
tables = lts.read_tables()
gdf_lts = lts.calculate_lts(gdf_adt.copy(), tables)

['table_mixed_1', 'table_mixed_2', 'table_mixed_3', 'table_mixed_4', 'table_mixed_5']
['table_bikelane_noparking_1', 'table_bikelane_noparking_2', 'table_bikelane_noparking_3']
['table_bikelane_yesparking_1', 'table_bikelane_yesparking_2', 'table_bikelane_yesparking_3', 'table_bikelane_yesparking_4']


In [36]:
print(f"{gdf_lts['LTS'].unique()=}")
print(f"{gdf_lts['LTS_mixed'].unique()=}")
print(f"{gdf_lts['centerline'].unique()=}")
print(f"{gdf_lts['lane_count'].unique()=}")
print(f"{gdf_lts['oneway'].unique()=}")

gdf_lts['LTS'].unique()=array([ 1.,  3.,  2., nan,  4.,  0.])
gdf_lts['LTS_mixed'].unique()=array([ 2.,  1.,  3., nan,  4.])
gdf_lts['centerline'].unique()=array(['no', 'yes'], dtype=object)
gdf_lts['lane_count'].unique()=array([2, 1, 3, 4, 5, 7])
gdf_lts['oneway'].unique()=array([False,  True])
